# Generated by Django 4.1.3 on 2024-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_cart_cart_id_alter_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=12, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
